# Generated by Django 2.2.5 on 2019-12-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
