# Generated by Django 2.2.3 on 2019-12-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20191212_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
