# Generated by Django 2.2.3 on 2019-10-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20191030_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planner.Project'),
        ),
    ]
