# Generated by Django 2.2.5 on 2019-12-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_project_users_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='creator',
        ),
    ]
